
#define DEFAULT_INI "[SWFModeOffset]\r\n\
SWF0offset=0\r\n\
SWF5offset=0\r\n\
SWF7offset=0\r\n\
SWF9offset=0\r\n\
SWF11offset=0\r\n\
[Default]\r\n\
Comment1='Script generated by Aegisub v2.1.2 RELEASE PREVIEW (SVN r1987, amz)'\r\n\
Comment2='http://www.aegisub.net'\r\n\
Comment3=\r\n\
PlayResX=1920\r\n\
PlayResY=1080\r\n\
DefaultFontname='MS UI Gothic'\r\n\
DefaultFontsize=90\r\n\
DefaultStyle='&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,5,0,1,2,2,1,10,10,10,0'\r\n\
RubiFontname='MS UI Gothic'\r\n\
RubiFontsize=50\r\n\
RubiStyle='&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,1,10,10,10,0'\r\n"
